// Portas/ligacoes HPS adaptadas de FPGAacademy DE1-SoC, MIT.
// Veja reference.json e LICENSE.fpgacademy.
module pbl2_hps_top (
    input wire CLOCK_50,
    input wire [3:0] KEY,
    input wire [9:0] SW,
    output wire [9:0] LEDR,
    output wire VGA_HS,
    output wire VGA_VS,
    output wire [7:0] VGA_R,
    output wire [7:0] VGA_G,
    output wire [7:0] VGA_B,
    output wire VGA_BLANK_N,
    output wire VGA_SYNC_N,
    output wire VGA_CLK,
    output wire [14:0] HPS_DDR3_ADDR,
    output wire [2:0] HPS_DDR3_BA,
    output wire HPS_DDR3_CAS_N,
    output wire HPS_DDR3_CKE,
    output wire HPS_DDR3_CK_N,
    output wire HPS_DDR3_CK_P,
    output wire HPS_DDR3_CS_N,
    output wire [3:0] HPS_DDR3_DM,
    inout wire [31:0] HPS_DDR3_DQ,
    inout wire [3:0] HPS_DDR3_DQS_N,
    inout wire [3:0] HPS_DDR3_DQS_P,
    output wire HPS_DDR3_ODT,
    output wire HPS_DDR3_RAS_N,
    output wire HPS_DDR3_RESET_N,
    input wire HPS_DDR3_RZQ,
    output wire HPS_DDR3_WE_N,
    output wire HPS_ENET_GTX_CLK,
    inout wire HPS_ENET_INT_N,
    output wire HPS_ENET_MDC,
    inout wire HPS_ENET_MDIO,
    input wire HPS_ENET_RX_CLK,
    input wire [3:0] HPS_ENET_RX_DATA,
    input wire HPS_ENET_RX_DV,
    output wire [3:0] HPS_ENET_TX_DATA,
    output wire HPS_ENET_TX_EN,
    inout wire [3:0] HPS_FLASH_DATA,
    output wire HPS_FLASH_DCLK,
    output wire HPS_FLASH_NCSO,
    inout wire HPS_GSENSOR_INT,
    inout wire [1:0] HPS_GPIO,
    inout wire HPS_I2C_CONTROL,
    inout wire HPS_I2C1_SCLK,
    inout wire HPS_I2C1_SDAT,
    inout wire HPS_I2C2_SCLK,
    inout wire HPS_I2C2_SDAT,
    inout wire HPS_KEY,
    inout wire HPS_LED,
    output wire HPS_SD_CLK,
    inout wire HPS_SD_CMD,
    inout wire [3:0] HPS_SD_DATA,
    output wire HPS_SPIM_CLK,
    input wire HPS_SPIM_MISO,
    output wire HPS_SPIM_MOSI,
    inout wire HPS_SPIM_SS,
    input wire HPS_UART_RX,
    output wire HPS_UART_TX,
    inout wire HPS_CONV_USB_N,
    input wire HPS_USB_CLKOUT,
    inout wire [7:0] HPS_USB_DATA,
    input wire HPS_USB_DIR,
    input wire HPS_USB_NXT,
    output wire HPS_USB_STP
);
    pbl2_hps_system u_system (
        .clk_clk(CLOCK_50),
        .reset_reset_n(KEY[0]),
        .gpu_board_key(KEY),
        .gpu_board_switches(SW),
        .gpu_board_leds(LEDR),
        .gpu_vga_hs(VGA_HS),
        .gpu_vga_vs(VGA_VS),
        .gpu_vga_r(VGA_R),
        .gpu_vga_g(VGA_G),
        .gpu_vga_b(VGA_B),
        .gpu_vga_blank_n(VGA_BLANK_N),
        .gpu_vga_sync_n(VGA_SYNC_N),
        .gpu_vga_pixel_clk(VGA_CLK),
        .memory_mem_a(HPS_DDR3_ADDR),
        .memory_mem_ba(HPS_DDR3_BA),
        .memory_mem_ck(HPS_DDR3_CK_P),
        .memory_mem_ck_n(HPS_DDR3_CK_N),
        .memory_mem_cke(HPS_DDR3_CKE),
        .memory_mem_cs_n(HPS_DDR3_CS_N),
        .memory_mem_ras_n(HPS_DDR3_RAS_N),
        .memory_mem_cas_n(HPS_DDR3_CAS_N),
        .memory_mem_we_n(HPS_DDR3_WE_N),
        .memory_mem_reset_n(HPS_DDR3_RESET_N),
        .memory_mem_dq(HPS_DDR3_DQ),
        .memory_mem_dqs(HPS_DDR3_DQS_P),
        .memory_mem_dqs_n(HPS_DDR3_DQS_N),
        .memory_mem_odt(HPS_DDR3_ODT),
        .memory_mem_dm(HPS_DDR3_DM),
        .memory_oct_rzqin(HPS_DDR3_RZQ),
        .hps_io_hps_io_gpio_inst_GPIO35(HPS_ENET_INT_N),
        .hps_io_hps_io_emac1_inst_TX_CLK(HPS_ENET_GTX_CLK),
        .hps_io_hps_io_emac1_inst_TXD0(HPS_ENET_TX_DATA[0]),
        .hps_io_hps_io_emac1_inst_TXD1(HPS_ENET_TX_DATA[1]),
        .hps_io_hps_io_emac1_inst_TXD2(HPS_ENET_TX_DATA[2]),
        .hps_io_hps_io_emac1_inst_TXD3(HPS_ENET_TX_DATA[3]),
        .hps_io_hps_io_emac1_inst_RXD0(HPS_ENET_RX_DATA[0]),
        .hps_io_hps_io_emac1_inst_MDIO(HPS_ENET_MDIO),
        .hps_io_hps_io_emac1_inst_MDC(HPS_ENET_MDC),
        .hps_io_hps_io_emac1_inst_RX_CTL(HPS_ENET_RX_DV),
        .hps_io_hps_io_emac1_inst_TX_CTL(HPS_ENET_TX_EN),
        .hps_io_hps_io_emac1_inst_RX_CLK(HPS_ENET_RX_CLK),
        .hps_io_hps_io_emac1_inst_RXD1(HPS_ENET_RX_DATA[1]),
        .hps_io_hps_io_emac1_inst_RXD2(HPS_ENET_RX_DATA[2]),
        .hps_io_hps_io_emac1_inst_RXD3(HPS_ENET_RX_DATA[3]),
        .hps_io_hps_io_qspi_inst_IO0(HPS_FLASH_DATA[0]),
        .hps_io_hps_io_qspi_inst_IO1(HPS_FLASH_DATA[1]),
        .hps_io_hps_io_qspi_inst_IO2(HPS_FLASH_DATA[2]),
        .hps_io_hps_io_qspi_inst_IO3(HPS_FLASH_DATA[3]),
        .hps_io_hps_io_qspi_inst_SS0(HPS_FLASH_NCSO),
        .hps_io_hps_io_qspi_inst_CLK(HPS_FLASH_DCLK),
        .hps_io_hps_io_gpio_inst_GPIO61(HPS_GSENSOR_INT),
        .hps_io_hps_io_gpio_inst_GPIO40(HPS_GPIO[0]),
        .hps_io_hps_io_gpio_inst_GPIO41(HPS_GPIO[1]),
        .hps_io_hps_io_gpio_inst_GPIO48(HPS_I2C_CONTROL),
        .hps_io_hps_io_i2c0_inst_SDA(HPS_I2C1_SDAT),
        .hps_io_hps_io_i2c0_inst_SCL(HPS_I2C1_SCLK),
        .hps_io_hps_io_i2c1_inst_SDA(HPS_I2C2_SDAT),
        .hps_io_hps_io_i2c1_inst_SCL(HPS_I2C2_SCLK),
        .hps_io_hps_io_gpio_inst_GPIO54(HPS_KEY),
        .hps_io_hps_io_gpio_inst_GPIO53(HPS_LED),
        .hps_io_hps_io_sdio_inst_CMD(HPS_SD_CMD),
        .hps_io_hps_io_sdio_inst_D0(HPS_SD_DATA[0]),
        .hps_io_hps_io_sdio_inst_D1(HPS_SD_DATA[1]),
        .hps_io_hps_io_sdio_inst_CLK(HPS_SD_CLK),
        .hps_io_hps_io_sdio_inst_D2(HPS_SD_DATA[2]),
        .hps_io_hps_io_sdio_inst_D3(HPS_SD_DATA[3]),
        .hps_io_hps_io_spim1_inst_CLK(HPS_SPIM_CLK),
        .hps_io_hps_io_spim1_inst_MOSI(HPS_SPIM_MOSI),
        .hps_io_hps_io_spim1_inst_MISO(HPS_SPIM_MISO),
        .hps_io_hps_io_spim1_inst_SS0(HPS_SPIM_SS),
        .hps_io_hps_io_uart0_inst_RX(HPS_UART_RX),
        .hps_io_hps_io_uart0_inst_TX(HPS_UART_TX),
        .hps_io_hps_io_gpio_inst_GPIO09(HPS_CONV_USB_N),
        .hps_io_hps_io_usb1_inst_D0(HPS_USB_DATA[0]),
        .hps_io_hps_io_usb1_inst_D1(HPS_USB_DATA[1]),
        .hps_io_hps_io_usb1_inst_D2(HPS_USB_DATA[2]),
        .hps_io_hps_io_usb1_inst_D3(HPS_USB_DATA[3]),
        .hps_io_hps_io_usb1_inst_D4(HPS_USB_DATA[4]),
        .hps_io_hps_io_usb1_inst_D5(HPS_USB_DATA[5]),
        .hps_io_hps_io_usb1_inst_D6(HPS_USB_DATA[6]),
        .hps_io_hps_io_usb1_inst_D7(HPS_USB_DATA[7]),
        .hps_io_hps_io_usb1_inst_CLK(HPS_USB_CLKOUT),
        .hps_io_hps_io_usb1_inst_STP(HPS_USB_STP),
        .hps_io_hps_io_usb1_inst_DIR(HPS_USB_DIR),
        .hps_io_hps_io_usb1_inst_NXT(HPS_USB_NXT)
    );
endmodule
